In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving 1) iris.csv to 1) iris (1).csv

In [9]:
import os
os.listdir()

['.config', '.ipynb_checkpoints', '1) iris.csv', 'sample_data']

In [10]:
data = pd.read_csv('1) iris.csv')
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [12]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [14]:
data = data.dropna()

In [15]:
data.duplicated().sum()

np.int64(3)

In [16]:
data = data.drop_duplicates()

In [17]:
data.to_csv("cleaned_1) iris.csv",index=False)

In [19]:
cleaned_data = pd.read_csv("cleaned_1) iris.csv")
cleaned_data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa